security:
  password_hashers:
    App\Entity\User:
      algorithm: auto
    App\Entity\Employe:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

    employe_provider:
      entity:
        class: App\Entity\Employe
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    employe:
      pattern: ^/employe
      lazy: true
      provider: employe_provider
      custom_authenticators:
        - App\Security\EmployeAuthenticator
      logout:
        path: employe_logout
        target: /employe/login

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticators:
        - App\Security\LoginFormAuthenticator
      logout:
        path: app_logout
        target: /

  access_control:
    - { path: ^/employe/login, roles: PUBLIC_ACCESS }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/employe, roles: ROLE_EMPLOYE }
    - { path: ^/user, roles: ROLE_USER }
    - { path: ^/register, roles: PUBLIC_ACCESS }
    - { path: ^/login, roles: PUBLIC_ACCESS }

  role_hierarchy:
    ROLE_ADMIN: [ROLE_EMPLOYE, ROLE_USER]
    ROLE_EMPLOYE: [ROLE_USER]
